<center>
<div style="font-weight:bold; font-size:large">
Ethik-Kommission<br />
der Medizinischen Universit&auml;t Wien<br />
und des<br />
Allgemeinen Krankenhauses der Stadt Wien Akh
</div>
<div style="font-size:large">
Borschkegasse 8b/6 - A-1090 Wien, Austria<br />
Tel.: +43 1 404 00 – 2147, 2244 & +43 1 404 00 – 1690
</div>
<div style="font-weight:bold; font-size:large"><br />
E-Mail: ethik-kom@meduniwien.ac.at<br />
www.meduniwien.ac.at/ethik
</div>
</center>
