<table>
	<tbody>
		<tr>
			<td style="vertical-align: top;">
				<img src="logo_big.png" width="13,69cm" height="2,44cm" alt="Ethik-Kommission der Medizinischen Universit&auml;t Wien" />
</div>
			</td>
			<td style="font-size: large; vertical-align: top; text-align: right; padding-top: 0.45cm; line-height: 0.45cm;">
				Borschkegasse 8b/6<br />
				A-1090 Wien, Austria<br /><br />
				T +43 1 404 00 – 2147, 2244<br />
				F +43 1 404 00 – 1690<br />
				ethik-kom@meduniwien.ac.at<br />
				ethikkommission.meduniwien.ac.at
			</td>
		</tr>
	</tbody>
</table>
<pdf:spacer height="2cm" />
