<div class="header">
    <img src="./media/logo_big.png" class="logo" alt="Ethik-Kommission der Medizinischen Universit&auml;t Wien" />

    <div class="address">
        Borschkegasse 8b/6<br />
        A-1090 Wien, Austria<br /><br />
        T +43 1 40 400 – 2147, 2244<br />
        F +43 1 40 400 – 1690<br />
        ethik-kom@meduniwien.ac.at<br />
        ethikkommission.meduniwien.ac.at
    </div>

    <div class="spacer">&nbsp;</div>
</div>
