# -*- coding: utf-8 -*- 

from south.db import db
from django.db import models
from core.models import *

class Migration:
    def forwards(self, orm):
        "Write your forwards migration here"
        for e in [ \
            EthicsCommission(address_1 = u'Gro\xdfe Mohrengasse 9', chairperson = u'Doz.Dr.Stefan Kudlacek', city = u'Wien', email = u'abteilung.interne@bbwien.at', fax = u'(01) 21121-2103', name = u'EK KH d. Barmh. Br\xfcder Wien', phone = u'(01) 21121-5075, -293.55', zip_code = u'A-1020'),
            EthicsCommission(address_1 = u'TownTown, Thomas-Klestil-Platz 8', chairperson = u'Dr.Karin Spacek', city = u'Wien', contactname = u'Reinhard Undeutsch', email = u'ik-eth@ma15.wien.gv.at', fax = u'(01) 4000-99-87754, -87755, -87756', name = u'EK der Stadt Wien gem\xe4\xdf KAG, AMG und MPG', phone = u'(01) 4000-87754, -87755, -87756', url = u'http://www.wien.gv.at/ma15/ethikkommission/index.htm', zip_code = u'A-1030'),
            EthicsCommission(address_1 = u'Nottendorfer Gasse 21', chairperson = u'Mag.Alexander Lang', city = u'Wien', contactname = u'Fr. Mag.Gabriele Sprengseis', email = u'forschung@w.roteskreuz.at', fax = u'(01) 79580-9730', name = u'EK Forschungsinstitut des Wiener Roten Kreuzes', phone = u'(01) 79580-1423 oder -1402', url = u'www.wrk.at/forschungsinstitut', zip_code = u'A-1030'),
            EthicsCommission(address_1 = u'Stumpergasse 13', chairperson = u'Prim.Dr.Boris Todoroff', city = u'Wien', email = u'office.wien@bhs.at', fax = u'(01) 599 88-4041', name = u'EK KH Barmh.Schwestern, Wien', phone = u'(01) 59988-2122', zip_code = u'A-1060'),
            EthicsCommission(address_1 = u'Skodagasse 32', chairperson = u'Prim.Dr.Dieter Volc', city = u'Wien', email = u'dieter.volc@pkj.at', fax = u'(01) 40114-5707', name = u'EK Confraternit\xe4t-Priv.Klin. Josefstadt und Priv.Klin. D\xf6bling', phone = u'(01) 40114-99', zip_code = u'A-1080'),
            EthicsCommission(address_1 = u'Borschkegasse 8b/E 06', chairperson = u'Univ.Prof.Dr.Ernst Singer', city = u'Wien', contactname = u'Fr. Dr.Christiane Druml', email = u'ethik-kom@meduniwien.ac.at', fax = u'(01) 40400-1690', name = u'EK Med.Universit\xe4t Wien', phone = u'(01) 40400-2147, -2248, -2241', url = u'www.meduniwien.ac.at/ethik', zip_code = u'A-1090'),
            EthicsCommission(address_1 = u'Kinderspitalgasse 6', chairperson = u'Dr.Roland Lavaulx-Vrecourt', city = u'Wien', email = u'verwaltungsdirektion@stanna.at', fax = u'(01) 40170-765', name = u'EK St.Anna Kinderspital', phone = u'(01) 40170-260', url = u'www.stanna.at', zip_code = u'A-1090'),
            EthicsCommission(address_1 = u'Kinderspitalgasse 10/15', chairperson = u'Univ.Prof.Dr.Gerhart Hitzenberger', city = u'Wien', email = u'office@ethikkommission-klinpharm.at', fax = u'(01) 408 4511-17', name = u'EK \xd6sterreichische Arbeitsgemeinschaft f\xfcr Klinische Pharmakologie und Therapie & Institut f\xfcr Hypertoniker', phone = u'(01) 408 4511-26', url = u'www.ethikkommission-klinpharm.at', zip_code = u'A-1090'),
            EthicsCommission(address_1 = u'Billrothstrasse 78', chairperson = u'Univ.Prof.Dr.Fritz Paschke', city = u'Wien', contactname = u'Univ.Doz.Dr.Werner Weissenhofer', email = u'w.weissenhofer@rudolfinerhaus.at', name = u'EK Privatkrankenanstalt Rudolfinerhaus', phone = u'(01) 360360', zip_code = u'A-1090'),
            EthicsCommission(address_1 = u'Kurbadstrasse 10', chairperson = u'(erreichbar \xfcber "Kontakt")', city = u'Wien', contactname = u'Fr. Erika Karner', email = u'office@rhz-oberlaa.at', fax = u'(01) 68009-9234', name = u'EK Rheuma-Zentrum Wien-Oberlaa', phone = u'(01) 68009-9231', zip_code = u'A-1100'),
            EthicsCommission(address_1 = u'Dornbacher Strasse 20-28', chairperson = u'OA Dr.Michael Peintinger', city = u'Wien', email = u'michael.peintinger@meduniwien.ac.at', fax = u'(01) 4865-631-343', name = u'EK KA des G\xf6ttlichen Heilandes', phone = u'(01) 4865-631-0', zip_code = u'A-1170'),
            EthicsCommission(address_1 = u'Hans-Sachs-Gasse 10-12', chairperson = u'DDr. Martin Bolz', city = u'Wien', email = u'b.savic@ekhwien.at', fax = u'(01) 40422-510', name = u'EK Evangelisches Krankenhaus', phone = u'(01) 40422-504', zip_code = u'A-1180'),
            EthicsCommission(address_1 = u'Adalbert-Stifter-Strasse 65', chairperson = u'Dr.Helmut K\xf6berl', city = u'Wien', email = u'helmut.koeberl@auva.at', fax = u'(01) 33111-379', name = u'EK der Allgemeinen Unfallversicherungsanstalt', phone = u'(01) 33111-458', zip_code = u'A-1200'),
            EthicsCommission(address_1 = u'c/o Abt. Sanit\xe4tsrecht u. Krankenanstalten', address_2 = u'Landhausplatz 1, Haus 15B', chairperson = u'Mag.Robert Bruckner', city = u'St.P\xf6lten', contactname = u'Fr. Astrid Dana', email = u'post.ethikkommission@noel.gv.at', fax = u'(02742) 9005 -12785', name = u'EK des Landes Nieder\xf6sterreich', phone = u'(02742) 9005 -12731, -15669, -15677', url = u'http://www.noel.gv.at/ethikkommission', zip_code = u'A-3109'),
            EthicsCommission(address_1 = u'Fadingerstrasse 1', chairperson = u'Univ.Doz.Dr.Rainer Sch\xf6fl', city = u'Linz', contactname = u'Fr. Sabine Metz', email = u'rainer.schoefl@elisabethinen.or.at', fax = u'(0732) 7676-4418', name = u'EK KH Elisabethinen', phone = u'(0732) 7676-4414', url = u'http://www.elisabethinen.or.at/30000_das_krankenhaus/30702_ethikk_start.htm', zip_code = u'A-4010'),
            EthicsCommission(address_1 = u'c/o Landesnervenklinik Wagner-Jauregg', address_2 = u'Wagner-Jauregg Weg 15', chairperson = u'Univ.Prof.Prim.Dr.Johannes Fischer', city = u'Linz', contactname = u'Univ.Prof.Prim.Dr.Johannes Fischer bzw. Fr. Dr.Elgin Drda', email = u'johannes.fischer@gespag.at', fax = u'0732/6921-25904 (Fischer) bzw. 0732/7720-215619 (Drda)', name = u'EK des Landes Ober\xf6sterreich', phone = u'0732/6921-25900 (Fischer) bzw. 0732/7720-15220 (Drda)', url = u'http://ooe-ethikkommission.at', zip_code = u'A-4020'),
            EthicsCommission(address_1 = u'Seilerst\xe4tte 2', chairperson = u'Prim.Univ.Prof.Dr.Kurt Lenz', city = u'Linz', email = u'kurt.lenz@bblinz.at', fax = u'(0732) 1099', name = u'EK KH Barmh.Br\xfcder Linz', phone = u'(0732) 7897', zip_code = u'A-4020'),
            EthicsCommission(address_1 = u'Seilerst\xe4tte 4', chairperson = u'Univ.Prof.Dr.Peter Siostrzonek', city = u'Linz', contactname = u'Fr. Hannelore Haunschmidt', email = u'ethik.linz@bhs.at', fax = u'(0732) 7677-7865', name = u'EK KH Barmh.Schwestern', phone = u'(0732) 7677-7262', zip_code = u'A-4020'),
            EthicsCommission(address_1 = u'Sebastian-Stief-Gasse 2', chairperson = u'Mag.Thomas Russegger', city = u'Salzburg', contactname = u'Fr. Mag.Silvia Peterbauer', email = u'ethikkommission@salzburg.gv.at', fax = u'(0662) 8042-2929', name = u'EK f.d.Bundesland Salzburg', phone = u'(0662) 8042-2375', url = u'http://www.salzburg.gv.at/ethikkommission', zip_code = u'A-5010'),
            EthicsCommission(address_1 = u'c/o Gesch\xe4ftsstelle', address_2 = u'Innrain 43', chairperson = u'Univ.Prof.DI Dr.Peter Lukas', city = u'Innsbruck', contactname = u'Fr. Mag.Karin Pardeller', email = u'Ethikkommission@i-med.ac.at', fax = u'(0512) 504-22295', name = u'EK Med.Universit\xe4t Innsbruck', phone = u'(0512) 504-25444, 22293', url = u'http://www.i-med.ac.at/ethikkommission', zip_code = u'A-6020'),
            EthicsCommission(address_1 = u'c/o Gesch\xe4ftsstelle', address_2 = u'Rathausstrasse 15', chairperson = u'Mag.pharm.Dr.Helmut Grimm', city = u'Bregenz', contactname = u'Fr. M.Achberger', email = u'ethikkomm.vlbg@bregenznet.at', fax = u'(05574) 58372', name = u'EK des Landes Vorarlberg', phone = u'(05574) 58372', url = u'http://www.ethikkommission-vorarlberg.at', zip_code = u'A-6900'),
            EthicsCommission(address_1 = u'Josef-Hyrtl-Platz 4', chairperson = u'PDir.DGKS Renate Peischl, MAS', city = u'Eisenstadt', email = u'renate.peischl@krages.at', fax = u'05 7979 5306', name = u'EK des Landes Burgenland gem\xe4\xdf KAG, AMG und MPG', phone = u'05 7979 30015', url = u'http://www.krages.at/Ethikkommission.31.0.html', zip_code = u'A-7000'),
            EthicsCommission(address_1 = u'c/o Amt d. Stmk.LR, FA8B - Gesundheitswesen', address_2 = u'Friedrichgasse 9', chairperson = u'HR Dr.Odo Feenstra', city = u'Graz', contactname = u'Fr. Dr.Brigitte Jauernik', email = u'brigitte.jauernik@stmk.gv.at', fax = u'(0316) 877-3555, -805840', name = u'EK gem\xe4\xdf AMG und MPG', phone = u'(0316) 877-5840', url = u'http://www.verwaltung.steiermark.at/cms/ziel/442986/DE/', zip_code = u'A-8010'),
            EthicsCommission(address_1 = u'Marschallgasse 12', chairperson = u'Prim.Univ.Doz.Dr.G\xfcnther Weber', city = u'Graz', email = u'guenther.weber@bbgraz.at', name = u'EK KH Barmh.Br\xfcder - Marschallgasse', phone = u'(0316) 7067-0', zip_code = u'A-8020'),
            EthicsCommission(address_1 = u'Bergstrasse 27', chairperson = u'Prof.Dr.Peter K\xf6ltringer', city = u'Graz', email = u'peter.koeltringer@bbegg.at', name = u'EK KH Barmh.Br\xfcder - Eggenberg', phone = u'(0316) 5989-0', zip_code = u'A-8020'),
            EthicsCommission(address_1 = u'Auenbruggerplatz 2', chairperson = u'Univ.Prof.DI.Dr.Peter H. Rehak', city = u'Graz', contactname = u'Fr. Mag.Andrea Berghofer', email = u'ethikkommission@medunigraz.at', fax = u'(0316) 385-4348', name = u'EK Med.Universit\xe4t Graz', phone = u'(0316) 385-3928, -2817', url = u'www.meduni-graz.at/ethikkommission/Graz/index.htm', zip_code = u'A-8036'),
            EthicsCommission(address_1 = u'c/o LKH Klagenfurt', address_2 = u'St.-Veiter-Strasse 45-47', chairperson = u'OA Dr.Gerhard Kober', city = u'Klagenfurt', contactname = u'Fr. Yvonne Wernig', email = u'Ethik@lkh-klu.at', fax = u'(0463) 538-23184', name = u'EK des Landes K\xe4rnten', phone = u'(0463) 538-29100', url = u'http://www.ethikkommission-kaernten.at', zip_code = u'A-9020'),
            ]:
            e.save()
    
    def backwards(self, orm):
        "Write your backwards migration here"
        for i in orm.EthicsCommission.objects.all():
            i.delete()
    
    models = {
        'core.amendment': {
            'date': ('django.db.models.fields.DateField', [], {}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'number': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'order': ('django.db.models.fields.IntegerField', [], {}),
            'submissionform': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['core.SubmissionForm']"})
        },
        'core.checklist': {
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'})
        },
        'core.diagnosticsapplied': {
            'count': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'period': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'submission': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['core.SubmissionForm']"}),
            'total': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'type': ('django.db.models.fields.CharField', [], {'max_length': '30'})
        },
        'core.document': {
            'absent': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'date': ('django.db.models.fields.DateTimeField', [], {}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'uuid_document': ('django.db.models.fields.SlugField', [], {'max_length': '32', 'db_index': 'True'}),
            'uuid_document_revision': ('django.db.models.fields.SlugField', [], {'max_length': '32', 'db_index': 'True'}),
            'version': ('django.db.models.fields.CharField', [], {'max_length': '20'})
        },
        'core.ethicscommission': {
            'address_1': ('django.db.models.fields.CharField', [], {'max_length': '60'}),
            'address_2': ('django.db.models.fields.CharField', [], {'max_length': '60'}),
            'chairperson': ('django.db.models.fields.CharField', [], {'max_length': '120', 'null': 'True'}),
            'city': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'contactname': ('django.db.models.fields.CharField', [], {'max_length': '120', 'null': 'True'}),
            'email': ('django.db.models.fields.EmailField', [], {'max_length': '75', 'null': 'True'}),
            'fax': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '60'}),
            'phone': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True'}),
            'url': ('django.db.models.fields.URLField', [], {'max_length': '200', 'null': 'True'}),
            'zip_code': ('django.db.models.fields.CharField', [], {'max_length': '10'})
        },
        'core.investigator': {
            'certified': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'email': ('django.db.models.fields.EmailField', [], {'max_length': '75'}),
            'fax': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'jus_practicandi': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'mobile': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '80'}),
            'organisation': ('django.db.models.fields.CharField', [], {'max_length': '80'}),
            'phone': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'sign_date': ('django.db.models.fields.DateField', [], {}),
            'specialist': ('django.db.models.fields.CharField', [], {'max_length': '80'}),
            'subject_count': ('django.db.models.fields.IntegerField', [], {}),
            'submission': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['core.SubmissionForm']"})
        },
        'core.investigatoremployee': {
            'firstname': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'organisation': ('django.db.models.fields.CharField', [], {'max_length': '80'}),
            'sex': ('django.db.models.fields.CharField', [], {'max_length': '1'}),
            'submission': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['core.Investigator']"}),
            'surname': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'title': ('django.db.models.fields.CharField', [], {'max_length': '40'})
        },
        'core.involvedcommissionsfornotification': {
            'commission': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['core.EthicsCommission']"}),
            'examiner_name': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '120'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'main': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'submission': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['core.NotificationForm']"})
        },
        'core.involvedcommissionsforsubmission': {
            'commission': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['core.EthicsCommission']"}),
            'examiner_name': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '120'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'main': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'submission': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['core.SubmissionForm']"})
        },
        'core.meeting': {
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'submissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['core.Submission']"})
        },
        'core.nontesteduseddrugs': {
            'dosage': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'generic_name': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'preparation_form': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'submission': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['core.SubmissionForm']"})
        },
        'core.notification': {
            'answer': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['core.NotificationAnswer']", 'null': 'True'}),
            'documents': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['core.Document']"}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'submission': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['core.Submission']", 'null': 'True'}),
            'workflow': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['core.Workflow']", 'null': 'True'})
        },
        'core.notificationanswer': {
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'workflow': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['core.Workflow']"})
        },
        'core.notificationform': {
            'SAE_count': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'SAE_report': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'SUSAR_count': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'SUSAR_report': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'aborted_on': ('django.db.models.fields.DateField', [], {'null': 'True'}),
            'aborted_subjects': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'amendment_report': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'comments': ('django.db.models.fields.TextField', [], {'default': "''"}),
            'date_of_vote': ('django.db.models.fields.DateField', [], {'null': 'True'}),
            'ek_number': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '40'}),
            'extension_of_vote': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'final_report': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'finished_on': ('django.db.models.fields.DateField', [], {'null': 'True'}),
            'finished_subjects': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'investigator': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['core.Investigator']", 'null': 'True'}),
            'notification': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'form'", 'null': 'True', 'to': "orm['core.Notification']"}),
            'reason_for_not_started': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'recruited_subjects': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'runs_till': ('django.db.models.fields.DateField', [], {'null': 'True'}),
            'signed_on': ('django.db.models.fields.DateField', [], {'null': 'True'}),
            'submission_form': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['core.SubmissionForm']", 'null': 'True'}),
            'yearly_report': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'})
        },
        'core.participatingcenter': {
            'address_1': ('django.db.models.fields.CharField', [], {'max_length': '60'}),
            'address_2': ('django.db.models.fields.CharField', [], {'max_length': '60'}),
            'city': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'country': ('django.db.models.fields.CharField', [], {'max_length': '4'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '60'}),
            'submission': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['core.SubmissionForm']"}),
            'zip_code': ('django.db.models.fields.CharField', [], {'max_length': '10'})
        },
        'core.submission': {
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'submissionreview': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['core.SubmissionReview']", 'null': 'True'}),
            'vote': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['core.Vote']", 'null': 'True'}),
            'workflow': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['core.Workflow']", 'null': 'True'})
        },
        'core.submissionform': {
            'additional_therapy_info': ('django.db.models.fields.TextField', [], {}),
            'already_voted': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'clinical_phase': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'commissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['core.EthicsCommission']"}),
            'date_of_protocol': ('django.db.models.fields.DateField', [], {}),
            'eudract_number': ('django.db.models.fields.CharField', [], {'max_length': '40', 'null': 'True'}),
            'german_abort_info': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'german_additional_info': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'german_aftercare_info': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'german_benefits_info': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'german_concurrent_study_info': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'german_consent_info': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'german_dataaccess_info': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'german_dataprotection_info': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'german_ethical_info': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'german_financing_info': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'german_inclusion_exclusion_crit': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'german_payment_info': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'german_preclinical_results': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'german_primary_hypothesis': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'german_project_title': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'german_protected_subjects_info': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'german_recruitment_info': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'german_relationship_info': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'german_risks_info': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'german_sideeffects_info': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'german_statistical_info': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'german_summary': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'insurance_address_1': ('django.db.models.fields.CharField', [], {'max_length': '80', 'null': 'True'}),
            'insurance_contract_number': ('django.db.models.fields.CharField', [], {'max_length': '60', 'null': 'True'}),
            'insurance_name': ('django.db.models.fields.CharField', [], {'max_length': '60', 'null': 'True'}),
            'insurance_phone': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True'}),
            'insurance_validity': ('django.db.models.fields.CharField', [], {'max_length': '60', 'null': 'True'}),
            'investigator_certified': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'investigator_email': ('django.db.models.fields.EmailField', [], {'max_length': '75'}),
            'investigator_fax': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'investigator_jus_practicandi': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'investigator_mobile': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'investigator_name': ('django.db.models.fields.CharField', [], {'max_length': '80'}),
            'investigator_organisation': ('django.db.models.fields.CharField', [], {'max_length': '80'}),
            'investigator_phone': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'investigator_specialist': ('django.db.models.fields.CharField', [], {'max_length': '80'}),
            'invoice_address1': ('django.db.models.fields.CharField', [], {'max_length': '60', 'null': 'True'}),
            'invoice_address2': ('django.db.models.fields.CharField', [], {'max_length': '60', 'null': 'True'}),
            'invoice_city': ('django.db.models.fields.CharField', [], {'max_length': '40', 'null': 'True'}),
            'invoice_contactname': ('django.db.models.fields.CharField', [], {'max_length': '80', 'null': 'True'}),
            'invoice_email': ('django.db.models.fields.EmailField', [], {'max_length': '75', 'null': 'True'}),
            'invoice_fax': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True'}),
            'invoice_name': ('django.db.models.fields.CharField', [], {'max_length': '80', 'null': 'True'}),
            'invoice_phone': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True'}),
            'invoice_uid': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True'}),
            'invoice_uid_verified_level1': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'invoice_uid_verified_level2': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'invoice_zip_code': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True'}),
            'isrctn_number': ('django.db.models.fields.CharField', [], {'max_length': '40', 'null': 'True'}),
            'medtech_ce_symbol': ('django.db.models.fields.NullBooleanField', [], {'null': 'True'}),
            'medtech_certified_for_exact_indications': ('django.db.models.fields.NullBooleanField', [], {'null': 'True'}),
            'medtech_certified_for_other_indications': ('django.db.models.fields.NullBooleanField', [], {'null': 'True'}),
            'medtech_checked_product': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'medtech_departure_from_regulations': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'medtech_manual_included': ('django.db.models.fields.NullBooleanField', [], {'null': 'True'}),
            'medtech_manufacturer': ('django.db.models.fields.CharField', [], {'max_length': '80', 'null': 'True'}),
            'medtech_product_name': ('django.db.models.fields.CharField', [], {'max_length': '80', 'null': 'True'}),
            'medtech_reference_substance': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'medtech_technical_safety_regulations': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'pharma_checked_substance': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'pharma_reference_substance': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'project_title': ('django.db.models.fields.CharField', [], {'max_length': '120'}),
            'project_type_2_1_1': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'project_type_2_1_2': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'project_type_2_1_2_1': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'project_type_2_1_2_2': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'project_type_2_1_3': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'project_type_2_1_4': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'project_type_2_1_4_1': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'project_type_2_1_4_2': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'project_type_2_1_4_3': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'project_type_2_1_5': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'project_type_2_1_6': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'project_type_2_1_7': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'project_type_2_1_8': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'project_type_2_1_9': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'protocol_number': ('django.db.models.fields.CharField', [], {'max_length': '40', 'null': 'True'}),
            'specialism': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'sponsor_address1': ('django.db.models.fields.CharField', [], {'max_length': '60', 'null': 'True'}),
            'sponsor_address2': ('django.db.models.fields.CharField', [], {'max_length': '60', 'null': 'True'}),
            'sponsor_city': ('django.db.models.fields.CharField', [], {'max_length': '40', 'null': 'True'}),
            'sponsor_contactname': ('django.db.models.fields.CharField', [], {'max_length': '80', 'null': 'True'}),
            'sponsor_email': ('django.db.models.fields.EmailField', [], {'max_length': '75', 'null': 'True'}),
            'sponsor_fax': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True'}),
            'sponsor_name': ('django.db.models.fields.CharField', [], {'max_length': '80', 'null': 'True'}),
            'sponsor_phone': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True'}),
            'sponsor_zip_code': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True'}),
            'study_plan_8_1_1': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'study_plan_8_1_10': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'study_plan_8_1_11': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'study_plan_8_1_12': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'study_plan_8_1_13': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'study_plan_8_1_14': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'study_plan_8_1_15': ('django.db.models.fields.TextField', [], {'default': "''", 'null': 'True'}),
            'study_plan_8_1_16': ('django.db.models.fields.TextField', [], {'default': "''", 'null': 'True'}),
            'study_plan_8_1_17': ('django.db.models.fields.TextField', [], {'default': "''", 'null': 'True'}),
            'study_plan_8_1_18': ('django.db.models.fields.TextField', [], {'default': "''", 'null': 'True'}),
            'study_plan_8_1_19': ('django.db.models.fields.TextField', [], {'default': "''", 'null': 'True'}),
            'study_plan_8_1_2': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'study_plan_8_1_20': ('django.db.models.fields.TextField', [], {'default': "''", 'null': 'True'}),
            'study_plan_8_1_21': ('django.db.models.fields.TextField', [], {'default': "''", 'null': 'True'}),
            'study_plan_8_1_22': ('django.db.models.fields.TextField', [], {'default': "''", 'null': 'True'}),
            'study_plan_8_1_3': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'study_plan_8_1_4': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'study_plan_8_1_5': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'study_plan_8_1_6': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'study_plan_8_1_7': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'study_plan_8_1_8': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'study_plan_8_1_9': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'study_plan_8_3_1': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'study_plan_8_3_2': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'study_plan_abort_crit': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'study_plan_alpha': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'study_plan_biometric_planning': ('django.db.models.fields.CharField', [], {'max_length': '120'}),
            'study_plan_datamanagement': ('django.db.models.fields.TextField', [], {}),
            'study_plan_dataprotection_anonalgoritm': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'study_plan_dataprotection_dvr': ('django.db.models.fields.CharField', [], {'max_length': '12'}),
            'study_plan_dataprotection_reason': ('django.db.models.fields.CharField', [], {'max_length': '120'}),
            'study_plan_dataquality_checking': ('django.db.models.fields.TextField', [], {}),
            'study_plan_dropout_ratio': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'study_plan_multiple_test_correction_algorithm': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'study_plan_planned_statalgorithm': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'study_plan_power': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'study_plan_statalgorithm': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'study_plan_statistics_implementation': ('django.db.models.fields.CharField', [], {'max_length': '120'}),
            'subject_childbearing': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'subject_count': ('django.db.models.fields.IntegerField', [], {}),
            'subject_duration': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'subject_duration_active': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'subject_duration_controls': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'subject_females': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'subject_males': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'subject_maxage': ('django.db.models.fields.IntegerField', [], {}),
            'subject_minage': ('django.db.models.fields.IntegerField', [], {}),
            'subject_noncompetents': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'subject_planned_total_duration': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'submitter_is_authorized_by_sponsor': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'submitter_is_coordinator': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'submitter_is_main_investigator': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'submitter_is_sponsor': ('django.db.models.fields.BooleanField', [], {'default': 'False', 'blank': 'True'}),
            'submitter_jobtitle': ('django.db.models.fields.CharField', [], {'max_length': '80'}),
            'submitter_name': ('django.db.models.fields.CharField', [], {'max_length': '80'}),
            'submitter_organisation': ('django.db.models.fields.CharField', [], {'max_length': '80'}),
            'submitter_sign_date': ('django.db.models.fields.DateField', [], {}),
            'substance_p_c_t_application_type': ('django.db.models.fields.CharField', [], {'max_length': '40', 'null': 'True'}),
            'substance_p_c_t_countries': ('django.db.models.fields.CharField', [], {'max_length': '300', 'null': 'True'}),
            'substance_p_c_t_final_report': ('django.db.models.fields.NullBooleanField', [], {'null': 'True'}),
            'substance_p_c_t_gcp_rules': ('django.db.models.fields.NullBooleanField', [], {'null': 'True'}),
            'substance_p_c_t_period': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'substance_p_c_t_phase': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True'}),
            'substance_preexisting_clinical_tries': ('django.db.models.fields.NullBooleanField', [], {'null': 'True'}),
            'substance_registered_in_countries': ('django.db.models.fields.CharField', [], {'max_length': '300', 'null': 'True'})
        },
        'core.submissionreview': {
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'workflow': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['core.Workflow']"})
        },
        'core.submissionset': {
            'documents': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['core.Document']"}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'submission': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'sets'", 'to': "orm['core.Submission']"}),
            'submissionform': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['core.SubmissionForm']"})
        },
        'core.therapiesapplied': {
            'count': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'period': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'submission': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['core.SubmissionForm']"}),
            'total': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'type': ('django.db.models.fields.CharField', [], {'max_length': '30'})
        },
        'core.vote': {
            'checklists': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['core.Checklist']"}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'submissionset': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['core.SubmissionSet']"}),
            'votereview': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['core.VoteReview']"}),
            'workflow': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['core.Workflow']"})
        },
        'core.votereview': {
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'workflow': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['core.Workflow']"})
        },
        'core.workflow': {
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'})
        }
    }
    
    complete_apps = ['core']
