# -*- coding: utf-8 -*-

# Caution: this file contains CONFIDENTIAL DATA

developers = (
    (u'Felix', u'Erkinger', u'felix@erkinger.at', 'm'),
    (u'Johannes', u'Dollinger', 'emulbreh@googlemail.com', 'm'),
    (u'Martin', u'Natano', 'natano@natano.net', 'm'),
    (u'Ludwig', u'Hammel', 'ludwig.hammel@gmail.com', 'm'),
    (u'Markus', u'Froehlich', 'froema@ep3.at', 'm'),
    (u'Peter', u'Rehak', 'peter.rehak@meduni-graz.at', 'm'),
    (u'Thomas', u'Neumann', 'tom@newtone.cc', 'm'),
    (u'Esther', u'Neumann', 'es_data@yahoo.de', 'f'),
    (u'Hudson', u'Windmill', 'windmill@example.org', 'f'),
)

staff_users = ()

board_members = ()

commissions = [{
    'uuid': u'23d805c6b5f14d8b9196a12005fd2961',
    'city': u'Wien',
    'fax': u'(01) 40400-1690',
    'chairperson': u'Univ.Prof.Dr.Ernst Singer',
    'name': u'Ethikkommission der Medizinischen Universit\u00e4t Wien',
    'url': u'ethikkommission.meduniwien.ac.at',
    'email': u'ethik-kom@meduniwien.ac.at',
    'phone': u'(01) 40400-2147, -2248, -2241',
    'address_1': u'Borschkegasse 8b/E 06',
    'contactname': u'Fr. Dr.Christiane Druml',
    'address_2': u'',
    'zip_code': u'A-1090',
}, {
    'uuid': u'7b51f38bde8a4161a0dc34647fc7e654',
    'city': u'Wien',
    'fax': u'(01) 21121-2103',
    'chairperson': u'Doz.Dr.Stefan Kudlacek',
    'name': u'EK KH d. Barmh. Br\u00fcder Wien',
    'url': None,
    'email': u'abteilung.interne@bbwien.at',
    'phone': u'(01) 21121-5075, -293.55',
    'address_1': u'Gro\u00dfe Mohrengasse 9',
    'contactname': None,
    'address_2': u'',
    'zip_code': u'A-1020',
}, {
    'uuid': u'85dc386061584fbe8549ce4e4d828fbd',
    'city': u'Wien',
    'fax': u'(01) 4000-99-87754, -87755, -87756',
    'chairperson': u'Dr.Karin Spacek',
    'name': u'EK der Stadt Wien gem\u00e4\u00df KAG, AMG und MPG',
    'url': u'http://www.wien.gv.at/ma15/ethikkommission/index.htm',
    'email': u'ik-eth@ma15.wien.gv.at',
    'phone': u'(01) 4000-87754, -87755, -87756',
    'address_1': u'TownTown, Thomas-Klestil-Platz 8',
    'contactname': u'Reinhard Undeutsch',
    'address_2': u'',
    'zip_code': u'A-1030',
}, {
    'uuid': u'd6a22c635a584521b107481ac18318f6',
    'city': u'Wien',
    'fax': u'(01) 79580-9730',
    'chairperson': u'Mag.Alexander Lang',
    'name': u'EK Forschungsinstitut des Wiener Roten Kreuzes',
    'url': u'www.wrk.at/forschungsinstitut',
    'email': u'forschung@w.roteskreuz.at',
    'phone': u'(01) 79580-1423 oder -1402',
    'address_1': u'Nottendorfer Gasse 21',
    'contactname': u'Fr. Mag.Gabriele Sprengseis',
    'address_2': u'',
    'zip_code': u'A-1030',
}, {
    'uuid': u'55ae93ec9df04d6abfc8d233ec5ccf8e',
    'city': u'Wien',
    'fax': u'(01) 599 88-4041',
    'chairperson': u'Prim.Dr.Boris Todoroff',
    'name': u'EK KH Barmh.Schwestern, Wien',
    'url': None,
    'email': u'office.wien@bhs.at',
    'phone': u'(01) 59988-2122',
    'address_1': u'Stumpergasse 13',
    'contactname': None,
    'address_2': u'',
    'zip_code': u'A-1060',
}, {
    'uuid': u'7cd6d52120b3474ba502931b9f60a5f3',
    'city': u'Wien',
    'fax': u'(01) 40114-5707',
    'chairperson': u'Prim.Dr.Dieter Volc',
    'name': u'EK Confraternit\u00e4t-Priv.Klin. Josefstadt und Priv.Klin. D\u00f6bling',
    'url': None,
    'email': u'dieter.volc@pkj.at',
    'phone': u'(01) 40114-99',
    'address_1': u'Skodagasse 32',
    'contactname': None,
    'address_2': u'',
    'zip_code': u'A-1080',
}, {
    'uuid': u'7df9ebaf15434709b09c3def9a6c8769',
    'city': u'Wien',
    'fax': u'(01) 40170-765',
    'chairperson': u'Dr.Roland Lavaulx-Vrecourt',
    'name': u'EK St.Anna Kinderspital',
    'url': u'www.stanna.at',
    'email': u'verwaltungsdirektion@stanna.at',
    'phone': u'(01) 40170-260',
    'address_1': u'Kinderspitalgasse 6',
    'contactname': None,
    'address_2': u'',
    'zip_code': u'A-1090',
}, {
    'uuid': u'f122f144616541d391fde2dcc761aff4',
    'city': u'Wien',
    'fax': u'(01) 408 4511-17',
    'chairperson': u'Univ.Prof.Dr.Gerhart Hitzenberger',
    'name': u'EK \u00d6sterreichische Arbeitsgemeinschaft f\u00fcr Klinische Pharmakologie',
    'url': u'www.ethikkommission-klinpharm.at',
    'email': u'office@ethikkommission-klinpharm.at',
    'phone': u'(01) 408 4511-26',
    'address_1': u'Kinderspitalgasse 10/15',
    'contactname': None,
    'address_2': u'',
    'zip_code': u'A-1090',
}, {
    'uuid': u'25b6744780434a3f96a1e43b405d3848',
    'city': u'Wien',
    'fax': None,
    'chairperson': u'Univ.Prof.Dr.Fritz Paschke',
    'name': u'EK Privatkrankenanstalt Rudolfinerhaus',
    'url': None,
    'email': u'w.weissenhofer@rudolfinerhaus.at',
    'phone': u'(01) 360360',
    'address_1': u'Billrothstrasse 78',
    'contactname': u'Univ.Doz.Dr.Werner Weissenhofer',
    'address_2': u'',
    'zip_code': u'A-1090',
}, {
    'uuid': u'd542994ced34403db841786a1c1ab892',
    'city': u'Wien',
    'fax': u'(01) 68009-9234',
    'chairperson': u'(erreichbar \u00fcber "Kontakt")',
    'name': u'EK Rheuma-Zentrum Wien-Oberlaa',
    'url': None,
    'email': u'office@rhz-oberlaa.at',
    'phone': u'(01) 68009-9231',
    'address_1': u'Kurbadstrasse 10',
    'contactname': u'Fr. Erika Karner',
    'address_2': u'',
    'zip_code': u'A-1100',
}, {
    'uuid': u'5615dfbaf8c8445d960d1e2cd9c00dc3',
    'city': u'Wien',
    'fax': u'(01) 4865-631-343',
    'chairperson': u'OA Dr.Michael Peintinger',
    'name': u'EK KA des G\u00f6ttlichen Heilandes',
    'url': None,
    'email': u'michael.peintinger@meduniwien.ac.at',
    'phone': u'(01) 4865-631-0',
    'address_1': u'Dornbacher Strasse 20-28',
    'contactname': None,
    'address_2': u'',
    'zip_code': u'A-1170',
}, {
    'uuid': u'4d3a2d5f138940f293ee87fe6ec1d5b2',
    'city': u'Wien',
    'fax': u'(01) 40422-510',
    'chairperson': u'DDr. Martin Bolz',
    'name': u'EK Evangelisches Krankenhaus',
    'url': None,
    'email': u'b.savic@ekhwien.at',
    'phone': u'(01) 40422-504',
    'address_1': u'Hans-Sachs-Gasse 10-12',
    'contactname': None,
    'address_2': u'',
    'zip_code': u'A-1180',
}, {
    'uuid': u'8d2950e3a0294f68bde647a54df6d823',
    'city': u'Wien',
    'fax': u'(01) 33111-379',
    'chairperson': u'Dr.Helmut K\u00f6berl',
    'name': u'EK der Allgemeinen Unfallversicherungsanstalt',
    'url': None,
    'email': u'helmut.koeberl@auva.at',
    'phone': u'(01) 33111-458',
    'address_1': u'Adalbert-Stifter-Strasse 65',
    'contactname': None,
    'address_2': u'',
    'zip_code': u'A-1200',
}, {
    'uuid': u'b17f32f604fa4452b5ff3a2baa9e0704',
    'city': u'St.P\u00f6lten',
    'fax': u'(02742) 9005 -12785',
    'chairperson': u'Mag.Robert Bruckner',
    'name': u'EK des Landes Nieder\u00f6sterreich',
    'url': u'http://www.noel.gv.at/ethikkommission',
    'email': u'post.ethikkommission@noel.gv.at',
    'phone': u'(02742) 9005 -12731, -15669, -15677',
    'address_1': u'c/o Abt. Sanit\u00e4tsrecht u. Krankenanstalten',
    'contactname': u'Fr. Astrid Dana',
    'address_2': u'Landhausplatz 1, Haus 15B',
    'zip_code': u'A-3109',
}, {
    'uuid': u'6688ce16a3b84d42b1531389e6039891',
    'city': u'Linz',
    'fax': u'(0732) 7676-4418',
    'chairperson': u'Univ.Doz.Dr.Rainer Sch\u00f6fl',
    'name': u'EK KH Elisabethinen',
    'url': u'http://www.elisabethinen.or.at/30000_das_krankenhaus/30702_ethikk_start.htm',
    'email': u'rainer.schoefl@elisabethinen.or.at',
    'phone': u'(0732) 7676-4414',
    'address_1': u'Fadingerstrasse 1',
    'contactname': u'Fr. Sabine Metz',
    'address_2': u'',
    'zip_code': u'A-4010',
}, {
    'uuid': u'e4dcd05a31ad475ca72dea7b84ef030e',
    'city': u'Linz',
    'fax': u'0732/6921-25904 (Fischer) bzw. 0732/7720-215619 (Drda)',
    'chairperson': u'Univ.Prof.Prim.Dr.Johannes Fischer',
    'name': u'EK des Landes Ober\u00f6sterreich',
    'url': u'http://ooe-ethikkommission.at',
    'email': u'johannes.fischer@gespag.at',
    'phone': u'0732/6921-25900 (Fischer) bzw. 0732/7720-15220 (Drda)',
    'address_1': u'c/o Landesnervenklinik Wagner-Jauregg',
    'contactname': u'Univ.Prof.Prim.Dr.Johannes Fischer bzw. Fr. Dr.Elgin Drda',
    'address_2': u'Wagner-Jauregg Weg 15',
    'zip_code': u'A-4020',
}, {
    'uuid': u'e269491bb9c040aaad6a5f11df343f38',
    'city': u'Linz',
    'fax': u'(0732) 1099',
    'chairperson': u'Prim.Univ.Prof.Dr.Kurt Lenz',
    'name': u'EK KH Barmh.Br\u00fcder Linz',
    'url': None,
    'email': u'kurt.lenz@bblinz.at',
    'phone': u'(0732) 7897',
    'address_1': u'Seilerst\u00e4tte 2',
    'contactname': None,
    'address_2': u'',
    'zip_code': u'A-4020',
}, {
    'uuid': u'1cca34032077445d95dabf7802fade28',
    'city': u'Linz',
    'fax': u'(0732) 7677-7865',
    'chairperson': u'Univ.Prof.Dr.Peter Siostrzonek',
    'name': u'EK KH Barmh.Schwestern',
    'url': None,
    'email': u'ethik.linz@bhs.at',
    'phone': u'(0732) 7677-7262',
    'address_1': u'Seilerst\u00e4tte 4',
    'contactname': u'Fr. Hannelore Haunschmidt',
    'address_2': u'',
    'zip_code': u'A-4020',
}, {
    'uuid': u'39cbb589ef044d27bceb6ee5ac796ae7',
    'city': u'Salzburg',
    'fax': u'(0662) 8042-2929',
    'chairperson': u'Mag.Thomas Russegger',
    'name': u'EK f.d.Bundesland Salzburg',
    'url': u'http://www.salzburg.gv.at/ethikkommission',
    'email': u'ethikkommission@salzburg.gv.at',
    'phone': u'(0662) 8042-2375',
    'address_1': u'Sebastian-Stief-Gasse 2',
    'contactname': u'Fr. Mag.Silvia Peterbauer',
    'address_2': u'',
    'zip_code': u'A-5010',
}, {
    'uuid': u'280414583b894c809a9baa8134d7fe4b',
    'city': u'Innsbruck',
    'fax': u'(0512) 504-22295',
    'chairperson': u'Univ.Prof.DI Dr.Peter Lukas',
    'name': u'EK Med.Universit\u00e4t Innsbruck',
    'url': u'http://www.i-med.ac.at/ethikkommission',
    'email': u'Ethikkommission@i-med.ac.at',
    'phone': u'(0512) 504-25444, 22293',
    'address_1': u'c/o Gesch\u00e4ftsstelle',
    'contactname': u'Fr. Mag.Karin Pardeller',
    'address_2': u'Innrain 43',
    'zip_code': u'A-6020',
}, {
    'uuid': u'183881da8200493aa7edd8bebeea75b9',
    'city': u'Bregenz',
    'fax': u'(05574) 58372',
    'chairperson': u'Mag.pharm.Dr.Helmut Grimm',
    'name': u'EK des Landes Vorarlberg',
    'url': u'http://www.ethikkommission-vorarlberg.at',
    'email': u'ethikkomm.vlbg@bregenznet.at',
    'phone': u'(05574) 58372',
    'address_1': u'c/o Gesch\u00e4ftsstelle',
    'contactname': u'Fr. M.Achberger',
    'address_2': u'Rathausstrasse 15',
    'zip_code': u'A-6900',
}, {
    'uuid': u'95821eba88f34b2195f96e747d7f6b16',
    'city': u'Eisenstadt',
    'fax': u'05 7979 5306',
    'chairperson': u'PDir.DGKS Renate Peischl, MAS',
    'name': u'EK des Landes Burgenland gem\u00e4\u00df KAG, AMG und MPG',
    'url': u'http://www.krages.at/Ethikkommission.31.0.html',
    'email': u'renate.peischl@krages.at',
    'phone': u'05 7979 30015',
    'address_1': u'Josef-Hyrtl-Platz 4',
    'contactname': None,
    'address_2': u'',
    'zip_code': u'A-7000',
}, {
    'uuid': u'6e7cfab5f8cd40df83c9de4fac9bb20f',
    'city': u'Graz',
    'fax': u'(0316) 877-3555, -805840',
    'chairperson': u'HR Dr.Odo Feenstra',
    'name': u'EK gem\u00e4\u00df AMG und MPG',
    'url': u'http://www.verwaltung.steiermark.at/cms/ziel/442986/DE/',
    'email': u'brigitte.jauernik@stmk.gv.at',
    'phone': u'(0316) 877-5840',
    'address_1': u'c/o Amt d. Stmk.LR, FA8B - Gesundheitswesen',
    'contactname': u'Fr. Dr.Brigitte Jauernik',
    'address_2': u'Friedrichgasse 9',
    'zip_code': u'A-8010',
}, {
    'uuid': u'75b5a9714f354a5b842aa01029148036',
    'city': u'Graz',
    'fax': None,
    'chairperson': u'Prim.Univ.Doz.Dr.G\u00fcnther Weber',
    'name': u'EK KH Barmh.Br\u00fcder - Marschallgasse',
    'url': None,
    'email': u'guenther.weber@bbgraz.at',
    'phone': u'(0316) 7067-0',
    'address_1': u'Marschallgasse 12',
    'contactname': None,
    'address_2': u'',
    'zip_code': u'A-8020',
}, {
    'uuid': u'9287fb0878b94f9f9d90b5582d1cefca',
    'city': u'Graz',
    'fax': None,
    'chairperson': u'Prof.Dr.Peter K\u00f6ltringer',
    'name': u'EK KH Barmh.Br\u00fcder - Eggenberg',
    'url': None,
    'email': u'peter.koeltringer@bbegg.at',
    'phone': u'(0316) 5989-0',
    'address_1': u'Bergstrasse 27',
    'contactname': None,
    'address_2': u'',
    'zip_code': u'A-8020',
}, {
    'uuid': u'e17ee744e4e840778f316cf3f79de6b4',
    'city': u'Graz',
    'fax': u'(0316) 385-4348',
    'chairperson': u'Univ.Prof.DI.Dr.Peter H. Rehak',
    'name': u'EK Med.Universit\u00e4t Graz',
    'url': u'www.meduni-graz.at/ethikkommission/Graz/index.htm',
    'email': u'ethikkommission@medunigraz.at',
    'phone': u'(0316) 385-3928, -2817',
    'address_1': u'Auenbruggerplatz 2',
    'contactname': u'Fr. Mag.Andrea Berghofer',
    'address_2': u'',
    'zip_code': u'A-8036',
}, {
    'uuid': u'ec9f179a52a04a7aa52446232c3fd4bd',
    'city': u'Klagenfurt',
    'fax': u'(0463) 538-23184',
    'chairperson': u'OA Dr.Gerhard Kober',
    'name': u'EK des Landes K\u00e4rnten',
    'url': u'http://www.ethikkommission-kaernten.at',
    'email': u'Ethik@lkh-klu.at',
    'phone': u'(0463) 538-29100',
    'address_1': u'c/o LKH Klagenfurt',
    'contactname': u'Fr. Yvonne Wernig',
    'address_2': u'St.-Veiter-Strasse 45-47',
    'zip_code': u'A-9020',
}]

from ecs.utils import Args

checklist_questions = {
    u'thesis_review': [
        Args('1', u'Geben Sie eine positive Empfehlung ab?'),  # XXX: dont change this number
    ],
    u'statistic_review': [
        Args('1', u'Ist das Studienziel ausreichend definiert?'),
        Args('2', u'Ist das Design der Studie geeignet, das Studienziel zu erreichen?'),
        Args('3', u'Ist die Studienpopulation ausreichend definiert?'),
        Args('4', u'Sind die Zielvariablen geeignet definiert?'),
        Args('5', u'Ist die statistische Analyse beschrieben, und ist sie adäquat?'),
        Args('6', u'Ist die Größe der Stichprobe ausreichend begründet?'),
    ],
    u'legal_review': [
        Args( '1', u"Anrede: entspricht?"),
        Args( '2', u"Hinweis auf Freiwilligkeit: entspricht?"),
        Args( '3', u"Hinweis auf jederzeitigen Abbruch: entspricht?"),
        Args( '4', u"Schwangerschaftspassus: entspricht?"),
        Args( '5', u"Versicherungspassus: entspricht?"),
        Args( '6', u"Name und Erreichbarkeit des Prüfarztes: entspricht?"),
        Args( '7', u"Hinweis auf Patientenanwaltschaft: entspricht?"),
        Args( '8', u"Vermeidung von Fremdwörtern: entspricht?"),
        Args( '9', u"Rechtschreibung und Grammatik: entspricht?"),
        Args('10', u"Die Patienteninformation entspricht in allen anderen Punkten den Anforderungen?"),
    ],
    u'insurance_review': [
        Args('1', u"Sind die Angaben zu Versicherung vollständig und adäquat?"),
    ],
    u'external_review': [
        Args('1a', u'Ist die Ausarbeitung des Projektes hinreichend um es begutachten zu können?'),
        Args('1b', u'Ist das Projekt vollständig (inkl. Angaben über Nebenwirkungen etc.)?',
            description=u'Bitte beurteilen Sie in diesem Zusammenhang auch die Vollständigkeit und Richtigkeit der in der Kurzfassung enthaltenen Aufstellung der studienbezogenen Maßnahmen!'),
        Args('2',  u'Ist die Fragestellung des Projektes relevant?'),
        Args('3',  u'Ist die angewandte Methodik geeignet, die Fragestellung zu beantworten?'),
        Args('3a', u'Findet sich im Protokoll eine Begründung der gewählten Fallzahl und eine Angabe über die geplante statistische Auswertung?'),
        Args('4a', u'Werden den Patienten/Probanden durch das Projekt besondere Risken zugemutet?',
            description=u'''- durch eine neue Substanz mit hoher Nebenwirkungsrate
            - durch Vorenthalten einer wirksamen Therapie
            - durch radioaktive Isotope
            - durch eine spezielle Dosierung von Medikamenten'''),
        Args('4b', u'Stehen diese Risken Ihrer Meinung nach in einem akzeptablen Verhältnis zum zu erwartenden Nutzen der Studie?'),
        Args('5a', u'Werden dem Patienten/Probanden durch die für die Studie notwendigen Untersuchungen besondere Belastungen bzw. Risken zugemutet?', inverted=True),
        Args('5b', u'Stehen diese Belastungen in einem akzeptablen Verhältnis zum zu erwartenden Nutzen der Studie ?'),
        Args('6',  u'Liegt ein Patienteninformationsblatt bei? Ist dieses ausreichend und verständlich?'),
    ],
    u'additional_review': [
        Args('1a', u'Ist die Ausarbeitung des Projektes hinreichend um es begutachten zu können?'),
        Args('1b', u'Ist das Projekt vollständig (inkl. Angaben über Nebenwirkungen etc.)?',
            description=u'Bitte beurteilen Sie in diesem Zusammenhang auch die Vollständigkeit und Richtigkeit der in der Kurzfassung enthaltenen Aufstellung der studienbezogenen Maßnahmen!'),
        Args('2',  u'Ist die Fragestellung des Projektes relevant?'),
        Args('3',  u'Ist die angewandte Methodik geeignet, die Fragestellung zu beantworten?'),
        Args('3a', u'Findet sich im Protokoll eine Begründung der gewählten Fallzahl und eine Angabe über die geplante statistische Auswertung?'),
        Args('4a', u'Werden den Patienten/Probanden durch das Projekt besondere Risken zugemutet?',
            description=u'''- durch eine neue Substanz mit hoher Nebenwirkungsrate
            - durch Vorenthalten einer wirksamen Therapie
            - durch radioaktive Isotope
            - durch eine spezielle Dosierung von Medikamenten'''),
        Args('4b', u'Stehen diese Risken Ihrer Meinung nach in einem akzeptablen Verhältnis zum zu erwartenden Nutzen der Studie?'),
        Args('5a', u'Werden dem Patienten/Probanden durch die für die Studie notwendigen Untersuchungen besondere Belastungen bzw. Risken zugemutet?', inverted=True),
        Args('5b', u'Stehen diese Belastungen in einem akzeptablen Verhältnis zum zu erwartenden Nutzen der Studie ?'),
        Args('6',  u'Liegt ein Patienteninformationsblatt bei? Ist dieses ausreichend und verständlich?'),
    ],
    u'gcp_review': [
        Args( '1', u'Sind die Allgemeinen Informationen ausreichend und korrekt angegeben?'),
        Args( '2', u'Sind die Hintergrundinformationen ausreichend und korrekt angegeben?'),
        Args( '3', u'Ist das Studienziel und der Studienzweck detailliert beschrieben?'),
        Args( '4', u'Ist das Studiendesign ausreichend dargelegt? (Endpunkte, Studienphase, Bias-Vermeidung, Prüfpräparat, Labelling, Dauer, Beendigung, Accountability, Randomisierung, Source Daten)'),
        Args( '5', u'Sind Patientenauswahl und Austritts- bzw. Abbruchkriterien ausreichend definiert? (Ein-/Ausschluss, Abbruch, Datenerhebung, follow up, Ersatz)'),
        Args( '6', u'Ist die Behandlung der Studienteilnehmer, samt erlaubter/nicht erlaubter Medikation und Überprüfungsverfahren ausreichend definiert?'),
        Args( '7', u'Sind die Efficacy Parameter sowie Methoden, zeitliche Planung und Erfassung & Analyse d. Efficacy Parameter ausreichend definiert?'),
        Args( '8', u'Ist Safety und Safety Reporting Parameter ausreichend definiert, und adäquat?'),
        Args( '9', u'Sind die Angaben zur statistischen Datenerhebung, -Auswertung, -Methoden ausreichend und adäquat?'),
        Args('10', u'Ist die Qualitätskontrolle und Qualitätssicherung ausreichend beschrieben und sind diese Angaben adäquat?'),
        Args('11', u'Sind Angaben zu ethischen Aspekten vorhanden?'),
        Args('12', u'Sind Angaben zu Datenerhebung, Dokumentation und Verarbeitung ausreichend definiert und sind diese adäquat?'),
        Args('13', u'Sind Angaben zu Finanzierung und Versicherung ausreichend definiert und sind diese adäquat?'),
        Args('14', u'Sind Angaben zur Regelung bzgl Publikation ausreichend definiert?'),
        Args('15', u'Anhang, wenn zutreffend?'),
    ],
    u'boardmember_review': [
        Args('1', u"Ist das Antragsformular korrekt und vollständig ausgefüllt?"),
        Args('2', u"Entspricht das Protokoll /der Prüfplan formal und inhaltlich den Richtlinien der „Guten wissenschaftlichen Praxis“ der MedUni Wien?"),
        Args('3', u"Entspricht/ entsprechen die Patienten/Probandeninformation(en) den formalen, inhaltlichen und sprachlichen Anforderungen?"),
    ],
    u'expedited_review': [
        Args('1', u'Geben Sie eine positive Empfehlung ab?'),  # XXX: dont change this number
        Args('2', u"Ist das Antragsformular korrekt und vollständig ausgefüllt?"),
        Args('3', u"Entspricht das Protokoll /der Prüfplan formal und inhaltlich den Richtlinien der „Guten wissenschaftlichen Praxis“ der MedUni Wien?"),
        Args('4', u"Entspricht/ entsprechen die Patienten/Probandeninformation(en) den formalen, inhaltlichen und sprachlichen Anforderungen?"),
    ],
    u'localec_review': [
        Args('1', u'Die Ethik-Kommissio bestätigt als lokale Ethik-Kommission im Sinne des §41b (5) die Eignung der Prüfer, seiner Mitarbeiter und die Angemessenheit der Einrichtungen in ihrem Zuständigkeitsbereich.'),
        
    ],
}
