import cicero

from ecs.integration.windmilldecorators import with_login


@with_login()
def test_new_message(client, times=1):
    client.click(id=u'userswitcher_input')
    client.waits.forPageLoad(timeout=u'20000')
    client.select(option=u'office1@example.org', id=u'userswitcher_input')
    client.click(link=u'Nachrichten')
    client.waits.forPageLoad(timeout=u'20000')
    client.waits.forElement(link=u'Neue Nachricht', timeout=u'8000')


    for i in xrange(times):
        client.click(link=u'Neue Nachricht')
        client.click(id=u'id_subject')
        subject = cicero.sentences(n=1, min=3, max=3)[0]
        client.type(text=subject, id=u'id_subject')
        client.click(id=u'id_receiver')
        client.select(option=u'presenter1@example.org', id=u'id_receiver')
        client.click(id=u'id_text')
        message = '\n'.join(cicero.sentences(n=5))
        client.type(text=message, id=u'id_text')
        client.click(value=u'Abschicken')

    client.click(value=u'33')
    client.waits.forPageLoad(timeout=u'20000')
    client.select(option=u'---------', id=u'userswitcher_input')
    client.click(xpath=u"//select[@id='userswitcher_input']/option[1]")


def test_10_new_messages():
    return
    # test_new_message(times=10)


@with_login()
def test_submit(client):
    client.click(id=u'userswitcher_input')
    client.waits.forPageLoad(timeout=u'20000')
    client.select(option=u'presenter1@example.org', id=u'userswitcher_input')
    client.click(xpath=u"//div[@id='usermenu']/ul/li[4]/span")
    client.click(link=u'Neuer Antrag')
    client.waits.forPageLoad(timeout=u'2000')
    client.waits.sleep(miliseconds=u'2000')
    client.check(id=u'id_project_type_basic_research')
    client.check(id=u'id_project_type_biobank')
    client.click(id=u'id_project_type_misc')
    client.type(text=u'bla3', id=u'id_project_type_misc')
    client.type(text=u'bla2', id=u'id_specialism')
    client.type(text=u'bla1', id=u'id_clinical_phase')
    client.type(text=u'bla3', id=u'id_external_reviewer_suggestions')
    client.click(link=u'Teilnehmer')
    client.click(id=u'id_subject_count')
    client.type(text=u'999', id=u'id_subject_count')
    client.type(text=u'999', id=u'id_subject_minage')
    client.type(text=u'999', id=u'id_subject_maxage')
    client.check(id=u'id_subject_males')
    client.check(id=u'id_subject_females')
    client.check(id=u'id_subject_childbearing')
    client.click(id=u'id_subject_duration')
    client.type(text=u'999', id=u'id_subject_duration')
    client.type(text=u'bla5', id=u'id_subject_duration')
    client.type(text=u'bla5', id=u'id_subject_duration_active')
    client.type(text=u'bla5', id=u'id_subject_duration_controls')
    client.type(text=u'bla8', id=u'id_subject_planned_total_duration')
    client.click(link=u'Kurzfassung')
    client.click(id=u'id_project_title')
    client.type(text=u'bla10', id=u'id_project_title')
    client.type(text=u'bla', id=u'id_german_project_title')
    client.type(text=u'bla8', id=u'id_project_title')
    client.type(text=u'bla10', id=u'id_german_project_title')
    client.type(text=u'bla5', id=u'id_protocol_number')
    client.type(text=u'blalong', id=u'id_german_summary')
    client.type(text=u'blamiddle', id=u'id_german_preclinical_results')
    client.type(text=u'blamiddle', id=u'id_german_primary_hypothesis')
    client.type(text=u'blamiddle', id=u'id_german_inclusion_exclusion_crit')
    client.type(text=u'blamiddle', id=u'id_german_ethical_info')
    client.type(text=u'bla10', id=u'id_german_protected_subjects_info')
    client.type(text=u'bla10', id=u'id_german_recruitment_info')
    client.type(text=u'bla10', id=u'id_german_consent_info')
    client.type(text=u'bla10', id=u'id_german_risks_info')
    client.type(text=u'bla15', id=u'id_german_benefits_info')
    client.type(text=u'bla10', id=u'id_german_relationship_info')
    client.type(text=u'bla5', id=u'id_german_concurrent_study_info')
    client.type(text=u'bla10', id=u'id_german_sideeffects_info')
    client.type(text=u'bla10', id=u'id_german_statistical_info')
    client.type(text=u'bla5', id=u'id_german_dataprotection_info')
    client.type(text=u'bla10', id=u'id_german_aftercare_info')
    client.type(text=u'bla10', id=u'id_german_payment_info')
    client.type(text=u'bla10', id=u'id_german_abort_info')
    client.type(text=u'bla10', id=u'id_german_dataaccess_info')
    client.type(text=u'bla15', id=u'id_german_financing_info')
    client.type(text=u'bla5', id=u'id_german_additional_info')
    client.click(link=u'Sponsor')
    client.click(id=u'id_sponsor_name')
    client.type(text=u'bla6', id=u'id_sponsor_name')
    client.select(option=u'Herr', id=u'id_sponsor_contact_gender')
    client.type(text=u'bla1', id=u'id_sponsor_contact_title')
    client.type(text=u'bla1', id=u'id_sponsor_contact_first_name')
    client.type(text=u'bla1', id=u'id_sponsor_contact_last_name')
    client.type(text=u'bla5', id=u'id_sponsor_address')
    client.type(text=u'99999', id=u'id_sponsor_zip_code')
    client.type(text=u'bla3', id=u'id_sponsor_city')
    client.type(text=u'999999999', id=u'id_sponsor_phone')
    client.type(text=u'999999999', id=u'id_sponsor_fax')
    client.type(text=u'bla@example.org', id=u'id_sponsor_email')
    client.click(link=u'Antragsteller')
    client.check(id=u'id_submitter_is_main_investigator')
    client.click(id=u'id_submitter_contact_gender')
    client.select(option=u'Frau', id=u'id_submitter_contact_gender')
    client.click(xpath=u"//select[@id='id_submitter_contact_gender']/option[2]")
    client.click(id=u'id_submitter_contact_title')
    client.type(text=u'bla2', id=u'id_submitter_contact_title')
    client.type(text=u'bla1', id=u'id_submitter_contact_first_name')
    client.type(text=u'bla1', id=u'id_submitter_contact_last_name')
    client.type(text=u'bla3', id=u'id_submitter_organisation')
    client.type(text=u'bla5', id=u'id_submitter_jobtitle')
    client.click(link=u'Ma\xdfnahmen')
    client.click(xpath=u"//div[@id='tabs-8']/div[1]/a")
    client.click(id=u'id_measure-0-type')
    client.type(text=u'bla3', id=u'id_measure-0-type')
    client.type(text=u'bla2', id=u'id_measure-0-count')
    client.type(text=u'bla2', id=u'id_measure-0-period')
    client.type(text=u'bla2', id=u'id_measure-0-total')
    client.click(xpath=u"//div[@id='tabs-8']/div[1]/a")
    client.click(id=u'id_measure-1-type')
    client.type(text=u'bla10', id=u'id_measure-1-type')
    client.type(text=u'bla2', id=u'id_measure-1-count')
    client.type(text=u'bla2', id=u'id_measure-1-period')
    client.type(text=u'bla2', id=u'id_measure-1-total')
    client.click(xpath=u"//div[@id='tabs-8']/div[1]/a")
    client.click(id=u'id_measure-2-type')
    client.type(text=u'bla5', id=u'id_measure-2-type')
    client.type(text=u'bla2', id=u'id_measure-2-count')
    client.type(text=u'bla2', id=u'id_measure-2-period')
    client.type(text=u'bla2', id=u'id_measure-2-total')
    client.click(xpath=u"//div[@id='tabs-8']/div[2]/a")
    client.click(id=u'id_routinemeasure-0-type')
    client.type(text=u'bla3', id=u'id_routinemeasure-0-type')
    client.type(text=u'bla2', id=u'id_routinemeasure-0-count')
    client.type(text=u'bla2', id=u'id_routinemeasure-0-period')
    client.type(text=u'bla2', id=u'id_routinemeasure-0-total')
    client.click(xpath=u"//div[@id='tabs-8']/div[2]/a")
    client.click(id=u'id_routinemeasure-1-type')
    client.type(text=u'bla8', id=u'id_routinemeasure-1-type')
    client.type(text=u'bla2', id=u'id_routinemeasure-1-count')
    client.type(text=u'bla2', id=u'id_routinemeasure-1-period')
    client.type(text=u'bla2', id=u'id_routinemeasure-1-total')
    client.click(xpath=u"//div[@id='tabs-8']/div[2]/a")
    client.click(id=u'id_routinemeasure-2-type')
    client.type(text=u'bla5', id=u'id_routinemeasure-2-type')
    client.type(text=u'bla2', id=u'id_routinemeasure-2-count')
    client.type(text=u'bla2', id=u'id_routinemeasure-2-period')
    client.type(text=u'bla2', id=u'id_routinemeasure-2-total')
    client.click(xpath=u"//div[@id='tabs-8']/div[3]/a")
    client.click(id=u'id_nontesteduseddrug-0-generic_name')
    client.type(text=u'bla2', id=u'id_nontesteduseddrug-0-generic_name')
    client.type(text=u'bla2', id=u'id_nontesteduseddrug-0-preparation_form')
    client.type(text=u'bla2', id=u'id_nontesteduseddrug-0-dosage')
    client.click(xpath=u"//div[@id='tabs-8']/div[3]/a")
    client.click(id=u'id_nontesteduseddrug-1-generic_name')
    client.type(text=u'bla5', id=u'id_nontesteduseddrug-1-generic_name')
    client.type(text=u'bla3', id=u'id_nontesteduseddrug-1-preparation_form')
    client.type(text=u'bla2', id=u'id_nontesteduseddrug-1-dosage')
    client.click(xpath=u"//div[@id='tabs-8']/div[3]/a")
    client.click(id=u'id_nontesteduseddrug-2-generic_name')
    client.type(text=u'bla2', id=u'id_nontesteduseddrug-2-generic_name')
    client.type(text=u'bla2', id=u'id_nontesteduseddrug-2-preparation_form')
    client.type(text=u'bla2', id=u'id_nontesteduseddrug-2-dosage')
    client.click(id=u'id_additional_therapy_info')
    client.type(text=u'bla8', id=u'id_additional_therapy_info')
    client.click(link=u'Biometrie')
    client.click(id=u'id_study_plan_blind')
    client.select(option=u'doppelblind', id=u'id_study_plan_blind')
    client.click(xpath=u"//select[@id='id_study_plan_blind']/option[4]")
    client.check(id=u'id_study_plan_placebo')
    client.click(id=u'id_study_plan_misc')
    client.type(text=u'bla3', id=u'id_study_plan_misc')
    client.type(text=u'bla3', id=u'id_study_plan_number_of_groups')
    client.type(text=u'bla3', id=u'id_study_plan_stratification')
    client.type(text=u'bla3', id=u'id_study_plan_sample_frequency')
    client.type(text=u'bla5', id=u'id_study_plan_primary_objectives')
    client.type(text=u'bla4', id=u'id_study_plan_null_hypothesis')
    client.type(text=u'bla3', id=u'id_study_plan_alternative_hypothesis')
    client.type(text=u'bla3', id=u'id_study_plan_secondary_objectives')
    client.type(text=u'bla3', id=u'id_study_plan_alpha')
    client.type(text=u'bla3', id=u'id_study_plan_power')
    client.type(text=u'bla3', id=u'id_study_plan_statalgorithm')
    client.type(text=u'bla3', id=u'id_study_plan_multiple_test_correction_algorithm')
    client.type(text=u'bla2', id=u'id_study_plan_dropout_ratio')
    client.check(id=u'id_study_plan_population_intention_to_treat')
    client.click(id=u'id_study_plan_abort_crit')
    client.type(text=u'bla4', id=u'id_study_plan_abort_crit')
    client.click(id=u'id_study_plan_planned_statalgorithm')
    client.type(text=u'bla3', id=u'id_study_plan_planned_statalgorithm')
    client.type(text=u'bla8', id=u'id_study_plan_dataquality_checking')
    client.type(text=u'bla5', id=u'id_study_plan_datamanagement')
    client.type(text=u'bla6', id=u'id_study_plan_biometric_planning')
    client.type(text=u'bla8', id=u'id_study_plan_statistics_implementation')
    client.type(text=u'bla5', id=u'id_study_plan_dataprotection_reason')
    client.type(text=u'bla4', id=u'id_study_plan_dataprotection_dvr')
    client.type(text=u'bla5', id=u'id_study_plan_dataprotection_anonalgoritm')
    client.click(link=u'Versicherung')
    client.click(id=u'id_insurance_name')
    client.type(text=u'bla5', id=u'id_insurance_name')
    client.type(text=u'bla3', id=u'id_insurance_address')
    client.type(text=u'99999999', id=u'id_insurance_phone')
    client.type(text=u'bla8', id=u'id_insurance_contract_number')
    client.type(text=u'bladate', id=u'id_insurance_validity')
    client.click(link=u'Auslandszentren')
    client.click(xpath=u"//div[@id='tabs-12']/div/a")
    client.click(id=u'id_foreignparticipatingcenter-0-name')
    client.type(text=u'bla3', id=u'id_foreignparticipatingcenter-0-name')
    client.type(text=u'bla3', id=u'id_foreignparticipatingcenter-0-investigator_name')
    client.click(xpath=u"//div[@id='tabs-12']/div/a")
    client.click(id=u'id_foreignparticipatingcenter-1-name')
    client.type(text=u'bla5', id=u'id_foreignparticipatingcenter-1-name')
    client.type(text=u'bla2', id=u'id_foreignparticipatingcenter-1-investigator_name')
    client.click(xpath=u"//div[@id='tabs-12']/div/a")
    client.click(id=u'id_foreignparticipatingcenter-2-name')
    client.type(text=u'bla4', id=u'id_foreignparticipatingcenter-2-name')
    client.type(text=u'bla3', id=u'id_foreignparticipatingcenter-2-investigator_name')
    client.click(link=u'Zentrum 1')
    client.click(id=u'id_investigator-0-organisation')
    client.type(text=u'bla6', id=u'id_investigator-0-organisation')
    client.type(text=u'bla5', id=u'id_investigator-0-organisation')
    client.type(text=u'999', id=u'id_investigator-0-subject_count')
    client.click(value=u'21')
    client.select(option=u'Ethikkomission der Medizinischen Universit\xe4t Wien', id=u'id_investigator-0-ethics_commission')
    client.click(xpath=u"//select[@id='id_investigator-0-ethics_commission']/option[2]")
    client.click(id=u'id_investigator-0-contact_gender')
    client.select(option=u'Herr', id=u'id_investigator-0-contact_gender')
    client.click(xpath=u"//select[@id='id_investigator-0-contact_gender']/option[3]")
    client.click(id=u'id_investigator-0-contact_title')
    client.type(text=u'bla2', id=u'id_investigator-0-contact_title')
    client.type(text=u'bla1', id=u'id_investigator-0-contact_first_name')
    client.type(text=u'bla1', id=u'id_investigator-0-contact_last_name')
    client.type(text=u'99999999999', id=u'id_investigator-0-phone')
    client.click(id=u'id_investigator-0-mobile')
    client.type(text=u'99999999999', id=u'id_investigator-0-mobile')
    client.type(text=u'99999999999', id=u'id_investigator-0-fax')
    client.click(id=u'id_investigator-0-email')
    client.type(text=u'bla@example.org', id=u'id_investigator-0-email')
    client.check(id=u'id_investigator-0-jus_practicandi')
    client.check(id=u'id_investigator-0-certified')
    client.click(id=u'id_investigator-0-specialist')
    client.type(text=u'bla5', id=u'id_investigator-0-specialist')
    client.click(id=u'id_investigatoremployee-0-sex')
    client.select(option=u'Herr', id=u'id_investigatoremployee-0-sex')
    client.click(xpath=u"//select[@id='id_investigatoremployee-0-sex']/option[2]")
    client.click(id=u'id_investigatoremployee-0-title')
    client.type(text=u'bla2', id=u'id_investigatoremployee-0-title')
    client.type(text=u'bla1', id=u'id_investigatoremployee-0-surname')
    client.type(text=u'bla1', id=u'id_investigatoremployee-0-firstname')
    client.type(text=u'bla3', id=u'id_investigatoremployee-0-organisation')
    client.click(id=u'submit-button')
    client.click(name=u'submit')
    client.waits.forPageLoad(timeout=u'20000')
    client.waits.forElement(timeout=u'8000', value=u'Ok')
    client.click(value=u'Ok')
    client.click(xpath=u"//select[@id='userswitcher_input']/option[12]")
    client.waits.forPageLoad(timeout=u'20000')
    client.select(option=u'---------', id=u'userswitcher_input')
    client.click(xpath=u"//select[@id='userswitcher_input']/option[1]")

