{% load i18n %}

<nav class="paginator">
  <ul class="pagination justify-content-center">
    {% if page.has_previous %}
        <li class="page-item">
            <a class="page-link" href="{{ request.path }}?page=1" data-page="1">
                <span class="fa fa-fast-backward"></span>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="{{ request.path }}?page={{ page.previous_page_number }}" data-page="{{ page.previous_page_number }}">
                <span class="fa fa-backward"></span>
            </a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <span class="page-link">
                <span class="fa fa-fast-backward"></span>
            </span>
        </li>
        <li class="page-item disabled">
            <span class="page-link">
                <span class="fa fa-backward"></span>
            </span>
        </li>
    {% endif %}
    <li class="page-item disabled">
        <span class="page-link">
            {% trans "Page" %} {{ page.number }} {% trans "of" %} {{ page.paginator.num_pages }}
        </span>
    </li>
    {% if page.has_next %}
        <li class="page-item">
            <a class="page-link" href="{{ request.path }}?page={{ page.next_page_number }}" data-page="{{ page.next_page_number }}">
                <span class="fa fa-forward"></span>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="{{ request.path }}?page={{ page.paginator.num_pages }}" data-page="{{ page.paginator.num_pages }}">
                <span class="fa fa-fast-forward"></span>
            </a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <span class="page-link">
                <span class="fa fa-forward"></span>
            </span>
        </li>
        <li class="page-item disabled">
            <span class="page-link">
                <span class="fa fa-fast-forward"></span>
            </span>
        </li>
    {% endif %}


  </ul>
</nav>
