{% load corepdf %}

<div class="header">
    <img class="logo" src="{% print_logo_url %}" alt="Logo" />

    <div class="address">
        Borschkegasse 8b/6<br />
        A-1090 Wien, Austria<br /><br />
        T +43 1 40 400 – 21470, 22440<br />
        F +43 1 40 400 – 16900<br />
        ethik-kom@meduniwien.ac.at<br />
        ethikkommission.meduniwien.ac.at
    </div>

    <div class="spacer">&nbsp;</div>
</div>
