{% load i18n %}

<script type="text/javascript">
    $(function(){
        var input = $('#{{ form_id }} select[name=task_types]');
        input.select2({
            width: '100%',
            dropdownParent: input.parent(),
        });

        $('#{{ form_id }}').find('select, input').change(function() {
            ecs.stopPageLoad();
            $('#{{ form_id }}').submit();
        });

        ecs.setupSubmitLinks('a.submit_parent');
    });
</script>

